Arkalogica
arkavidia-hmif/arkavidia-backend pull request #48
Opened 2020-10-19 12:45 UTC by ravielze

Usecase/Business logic di views.py belum selesai
Baru ada serializers, models sama masuk ke docs apinya.

2020-10-19 13:26 UTC, hashshura commented on arkav/arkalogica/models.py
> +    questions = models.ManyToManyField(to=Question, related_name='session')
Pindah jadi `ForeignKey` di `Question`? Karena OneToMany

2020-10-19 13:26 UTC, hashshura commented on arkav/arkalogica/models.py
> +        return Session.objects.filter(question__id=self.id).count()
```python
return self.questions.count()
```

Fungsinya bakal kepakai di mana ya? Kalau belom yakin bakal kepakai sebenernya mending gausah ada dulu sih

2020-10-19 13:26 UTC, hashshura commented on arkav/arkalogica/models.py
> +    question = models.ForeignKey(to=Question, related_name='choice', on_delete=models.CASCADE)
Sebenernya lebih enak kalau `related_name='choices'` biar nanti manggilnya dari objek `Question` gini: `question.choices`. Biar tahu kalau choices = multiple objects

2020-10-19 13:26 UTC, hashshura commented on arkav/arkalogica/models.py
> +    tag = models.CharField(max_length=1)
```python
choice = models.ForeignKey(to=Choice...)
```

Kalo butuh tagnya, bisa:
```python
@property
def tag(self):
  return self.choice.tag
```

2020-10-19 13:26 UTC, hashshura commented on arkav/arkalogica/models.py
> +        choices = Choice.objects.filter(question=self.question).all()
Kalau pakai yang atas, ntar bisa:

```python
return self.choice.is_correct
```

2020-10-19 13:47 UTC, ravielze commented on arkav/arkalogica/models.py
> +    questions = models.ManyToManyField(to=Question, related_name='session')
aku mikirnya satu question bisa dibanyak sesi sih

2020-10-19 13:47 UTC, ravielze commented on arkav/arkalogica/models.py
> +        return Session.objects.filter(question__id=self.id).count()
oke

2020-10-19 13:47 UTC, ravielze commented on arkav/arkalogica/models.py
> +    question = models.ForeignKey(to=Question, related_name='choice', on_delete=models.CASCADE)
oke

2020-10-19 13:48 UTC, ravielze commented on arkav/arkalogica/models.py
> +    tag = models.CharField(max_length=1)
oke

2020-10-19 13:48 UTC, ravielze commented on arkav/arkalogica/models.py
> +        choices = Choice.objects.filter(question=self.question).all()
oke

2020-10-27 02:25 UTC, hashshura commented on arkav/arkalogica/models.py
> +        return self.choice.tag
```python
@property
def tag(self):
  return self.choice.tag
```
Biar ntar manggilnya `answer.tag` karena esensinya dia atribut (bukan fungsi/ada logicnya). Btw `tag`-nya dihilangin dari `Choice` ya? Sebenernya ada gapapa sih biar kalo bikin kunjaw, jelas A B C D nya yang mana

2020-10-30 10:49 UTC, jonesnapoleon requested changes

2020-10-30 10:49 UTC, jonesnapoleon commented on arkav/arkalogica/views.py
> +    permission_classes = (IsAuthenticated,)
permissionclass nya gaboleh cuma isauthenticated, tapi yg ada daftar arkalogica jg

2020-10-30 10:49 UTC, jonesnapoleon commented on arkav/arkalogica/views.py
> +    permission_classes = (IsAuthenticated,)
sisasnya fine with me

2020-11-01 09:23 UTC, ravielze commented on arkav/arkalogica/views.py
> +    permission_classes = (IsAuthenticated,)
oke

2020-11-16 02:46 UTC, jrandiny commented
Fix conflictnya ya

2020-11-16 15:20 UTC, jrandiny commented
Move to #53

2020-11-16 15:20 UTC, closed without merging